### ISSUE TITLE
Washing Blood Stained Shoes Doesnt Remove Blood Overlay

### ISSUE THREAD

**Issue by wesoda25** [KeplerStation/KeplerStation#1024] opened 2019-11-11 20:23 UTC
Issue reported from  Round ID: 184 (KeplerStation)

Reporting client version: 512

Get shoes bloody. Wash them in sink. Shoe sprite remains bloody, but on person sprite is clean, and doesn't leave a trail.

**Comment by AffectedArc07** [comment] 2019-11-13 12:09
This was forgotten when I did the blood rework. Will fix soon.

**Comment by AffectedArc07** [comment] 2019-11-16 16:28
![KPb5SfmErw](https://user-images.githubusercontent.com/25063394/68996146-0c1fa480-088e-11ea-9ed1-f3aa65b1b29c.gif)
Cannot reproduce

**Comment by wesoda25** [comment] 2019-11-20 01:39
black shoes I used chef sink if it helps?

**Comment by wesoda25** [comment] 2019-11-20 01:39
Also I believe it was monkey blood, which might be the issue

**Comment by AffectedArc07** [comment] 2019-11-22 10:39
Tried with monkey blood using the chef sink, still cannot reproduce.

**Comment by AffectedArc07** [comment] 2019-11-22 10:39
Closed as this is not reproducible, and a PR has been merged which I believe fixes this.

**Closed** 2019-11-22 10:39 UTC
Labels: Cant Reproduce, Oversight
